name: PR

on:
  pull_request:

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI / ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.runner }}
    strategy:
      matrix:
        os:
          - name: "Linux amd64"
            runner: "ubuntu-24.04"
          - name: "Linux arm64"
            runner: "ubuntu-24.04-arm"
          - name: "MacOS"
            runner: "macos-latest"
          - name: "Windows"
            runner: "windows-latest"
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build
        run: go build -buildvcs=false ./cmd/

      - name: Test
        run: go test -v -coverprofile='coverage.out' -covermode=atomic ./...

      - uses: codecov/codecov-action@v5
        continue-on-error: true
        with:
          files: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
